# EX: Evaluating a Reflex Agent

In this exercise, we will build a basic Reflex Agent. It takes in a raw sensor reading (a radar cross-section size) and immediately outputs a classification.

More importantly, we will program the agent to recognize its own limitations. If the data is ambiguous, the agent will refuse to make a blind guess and will instead output a [HUMAN EVALUATION REQUIRED] flag.

**Steps Performed:**

* **Define the agent:** Define the Reflex Agent's rules (mapping inputs to specific actions).

* **Set thresholds for uncertainty:** Define the uncertainty threshold where the AI knows it cannot be trusted.

* **Use the model:** Feed the agent a stream of incoming radar data and observe how it handles clear threats vs. edge cases.


In [1]:

def tactical_reflex_agent(radar_cross_section_sqm):
    """
    A simple reflex agent that classifies radar tracks based on size.
    It refuses to classify ambiguous data, requesting human evaluation.
    """
    # Rule 1: Very small objects are likely birds or drones
    if radar_cross_section_sqm < 0.5:
        return "CLASSIFICATION: sUAS / Drone"
    
    # Rule 2: Very large objects are likely commercial aircraft
    elif radar_cross_section_sqm > 50.0:
        return "CLASSIFICATION: Commercial Heavy"
    
    # Rule 3: The "Ambiguous Zone" (e.g., fighter jets vs. small civilian planes)
    else:
        # The agent recognizes it lacks the context to make a safe decision
        return "WARNING: Ambiguous signature. [HUMAN EVALUATION REQUIRED]"

# Simulated incoming radar data (in square meters)
incoming_tracks = [0.1, 85.0, 2.5, 0.4, 15.0]

print("--- AI RADAR CLASSIFICATION SYSTEM ONLINE ---")
for track in incoming_tracks:
    decision = tactical_reflex_agent(track)
    print(f"Track Size {track:04.1f} sqm -> {decision}")




--- AI RADAR CLASSIFICATION SYSTEM ONLINE ---
Track Size 00.1 sqm -> CLASSIFICATION: sUAS / Drone
Track Size 85.0 sqm -> CLASSIFICATION: Commercial Heavy
Track Size 02.5 sqm -> WARNING: Ambiguous signature. [HUMAN EVALUATION REQUIRED]
Track Size 00.4 sqm -> CLASSIFICATION: sUAS / Drone
Track Size 15.0 sqm -> WARNING: Ambiguous signature. [HUMAN EVALUATION REQUIRED]


## Interpreting the Results
```{figure} ../../figures/reflex_agent.png
---
width: 80%
align: center
name: simple-reflex-agent
---
A simple reflex agent implemented in Python.
```

When you run this code, the agent easily handles the obvious extremes (0.1 and 85.0). However, when it encounters a 2.5 sqm or 15.0 sqm track, it does not blindly guess. It flags the track for human review. This perfectly demonstrates why human-on-the-loop evaluation is critical: AI systems are bound by their rigid rules and lack the common-sense intuition required to resolve tactical ambiguity safely.